version: '3'
services:
  nodejs:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: my-secret-pw
      DB_DATABASE: mydb
    networks:
      - my-network

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: mydb
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
